### ISSUE TITLE
Missing absolute value in 3.8 b)

### ISSUE THREAD

**Issue by jpl126** [ArthurZC23/Machine-Learning-A-Probabilistic-Perspective-Solutions#4]
Hi, 
IMHO in 3.8 b) there should be abs(x_n+1) instead of x_n+1.
If x_n+1 will be - 100*a its probablilty will be 0.
![abs](https://user-images.githubusercontent.com/33606018/55352413-18065400-54c1-11e9-9dbe-3a9455bc71e0.png)

Thanks for this repo!

https://github.com/ArthurZC23/Machine-Learning-A-Probabilistic-Perspective-Solutions/blob/master/3/8.pdf

**Comment by ArthurZC23** [comment]
Hey jpl126. You're right, the absolute value was missing. Sometimes I don't copy all the expressions correctly from my notebook to LaTex. Thanks for pointing that out.
Cheers.

**Comment by ArthurZC23** [comment]
Fix with commit 29f37f38c9f2d20fe092a90cbb107f8c380576ef.
